apiVersion: 1

datasources:
  - name: Loki
    uid: bcd-loki
    type: loki
    access: proxy
    url: ${GRAFANA_DS_LOKI_URL}
    isDefault: false
    editable: true

  - name: Tempo
    uid: bcd-tempo
    type: tempo
    access: proxy
    url: ${GRAFANA_DS_TEMPO_URL}
    isDefault: false
    editable: true
