server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: ${PROMTAIL_LOKI_PUSH_URL}

scrape_configs:
  - job_name: better-cloud-drive-runtime
    static_configs:
      - targets:
          - localhost
        labels:
          job: better-cloud-drive
          service: backend
          log_type: runtime
          __path__: /var/log/cloud-drive/runtime.log*

  - job_name: better-cloud-drive-audit
    static_configs:
      - targets:
          - localhost
        labels:
          job: better-cloud-drive
          service: backend
          log_type: audit
          __path__: /var/log/cloud-drive/audit.log*
