appendonly yes
appendfsync everysec

save 900 1
save 300 10
save 60 10000

maxmemory-policy noeviction

tcp-keepalive 300
timeout 0

protected-mode no

dir /data
dbfilename dump.rdb
appendfilename "appendonly.aof"

loglevel notice

slowlog-log-slower-than 10000
slowlog-max-len 128

hash-max-listpack-entries 512
hash-max-listpack-value 64

list-max-listpack-size -2
